using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using ONNX.Common.Tensor;

namespace ONNX.Common.Helpers
{
    public static class DebugHelpers
    {
        public static string GetSpanPrintString<T>(this ReadOnlySpan<T> span)
        {
            return span.ToArray().GetArrPrintString();
        }
        
        public static string GetArrPrintString<T>(this T[] arr)
        {
            // It has to include commas and the array brackets as well...
            var stringBuilder = new StringBuilder(arr.Length * 2);

            stringBuilder.Append('[');
            
            const string SEPARATOR = ", ";
            
            foreach (var item in arr)
            {
                stringBuilder.Append(item);
                stringBuilder.Append(SEPARATOR);
            }
            
            var separatorLength = SEPARATOR.Length;
            stringBuilder.Remove(stringBuilder.Length - separatorLength, separatorLength);
            
            stringBuilder.Append(']');
            
            return stringBuilder.ToString();
        }
        
        // Generated by ChatGPT
        public static void PrintTensor<T>(this ManagedTensor<T> managedTensor)
            where T: unmanaged
        {
            var tensor = managedTensor.OnnxDenseTensor;
            
            // Get the shape of the tensor
            var shape = string.Join("x", tensor.Dimensions.ToArray());
            
            // Print out the flat array
            Console.WriteLine($"Tensor Shape: {shape}");
            Console.WriteLine("Values:");
            
            for (int i = 0; i < tensor.Length; i++)
            {
                Console.Write(tensor.GetValue(i) + " ");
            }
            Console.WriteLine();
        }

        public static void PrintOnnxValueNameAndDimensions(this IEnumerable<NamedOnnxValue> onnxValues)
        {
            foreach (var onnxValue in onnxValues)
            {
                var val = onnxValue.Value;
                
                ReadOnlySpan<int> dimensions;

                if (val is DenseTensor<float> fTensor)
                {
                    dimensions = fTensor.Dimensions;
                }
                
                else if (val is DenseTensor<long> lTensor)
                {
                    dimensions = lTensor.Dimensions;
                }
                
                else if (val is DenseTensor<bool> bTensor)
                {
                    dimensions = bTensor.Dimensions;
                }
                
                else if (val is DenseTensor<double> dTensor)
                {
                    dimensions = dTensor.Dimensions;
                }

                else
                {
                    throw new NotSupportedException();
                }
                
                
                Console.WriteLine($"Name: {onnxValue.Name} | Dimensions: {dimensions.GetSpanPrintString()}");
            }
        }
    }
}