<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0; net9.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.0" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime.Extensions" Version="0.14.0" />
        <PackageReference Include="System.Numerics.Tensors" Version="10.0.0-preview.5.25277.114" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\Embedded\*.*" Visible="true" />
    </ItemGroup>

    <!-- This is required for some reason ( For MacOS at least, I think it is because I'm on Sequoia ). -->
    <!-- I stole the dylib from the nuget package folder of Microsoft.ML.OnnxRuntime.Extensions -->
    <!-- Sometimes OSX might block the dylib file, here's how to allow it: https://imgur.com/a/MGXOgFX -->
    <ItemGroup>
        <None Update="Resources/ortextensions.dylib"
              Condition="$([MSBuild]::IsOSPlatform('OSX'))"
              Visible="false">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>ortextensions.dylib</Link>
        </None>
    </ItemGroup>
    
    <!--  https://youtrack.jetbrains.com/issue/RIDER-26906 -->
    <Target Name="ExcludeAnnoyingDylib" AfterTargets="ResolveAssemblyReferences">
        <ItemGroup>
            <None Update="@(None)">
                <Visible>false</Visible>
            </None>
        </ItemGroup>
    </Target>

    <PropertyGroup>
        <!-- Suppress warnings about using experimental feature -->
        <NoWarn>SYSLIB5001</NoWarn>
    </PropertyGroup>
    
</Project>
