<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOsPlatform('Windows'))">
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOsPlatform('OSX'))">
        <!-- <RuntimeIdentifier>osx-x64</RuntimeIdentifier> -->
        <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\ONNX.Common\ONNX.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NoParamlessCtor" Version="1.1.1-alpha.31.cb558c4" />
      <PackageReference Include="Tokenizers.NET" Version="1.1.0-alpha.50-b9fd3da" />
    </ItemGroup>
    
    <ItemGroup>
        <!-- OSX ARM64 -->
        <Content Include="$(MSBuildProjectDirectory)/Resources/jina_tokenizer.json"
                 CopyToOutputDirectory="PreserveNewest"
                 Condition="Exists('$(MSBuildProjectDirectory)/Resources/jina_tokenizer.json')"
        />
    </ItemGroup>

    <PropertyGroup>
        <!-- Suppress warnings about using experimental feature -->
        <NoWarn>SYSLIB5001</NoWarn>
    </PropertyGroup>

</Project>
